name: xiaomi-nabu-dualboot-esp
on:
  workflow_call:
    inputs:
      desktop:
        type: string
        required: true

run-name: 'Xiaomi Pad 5 ESP (${{ inputs.desktop }})'

jobs:
  esp:
    runs-on: ubuntu-24.04
    steps:
      - name: Setup
        run: sudo apt update && sudo apt install -y tree 7zip

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: dualboot

      - name: Download release.7z
        run: |
          curl -L https://github.com/pocketblue/pocketblue/releases/latest/download/pocketblue-xiaomi-nabu-${{ inputs.desktop }}-43.7z --output release.7z
          7z x -orelease release.7z

      - name: Download rEFInd artifact 
        uses: actions/download-artifact@v4
        with:
          name: rEFInd
          path: refind

      - name: Download Reboot2Android artifact
        uses: actions/download-artifact@v4
        with:
          name: Reboot2Android
          path: reboot2android

      - name: Generate ESP
        run: sudo bash ./dualboot/devices/xiaomi-nabu/scripts/generate-esp.sh

      - name: Compress ESP
        run: zip ${{ inputs.desktop }}.zip esp.raw

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.desktop }}
          path: ${{ inputs.desktop }}.zip
          retention-days: 7
